import { supabase } from '../config/supabaseClient';

export const productService = {
  async getProducts() {
    if (!supabase) throw new Error('Supabase client not initialized.');
    const { data, error } = await supabase.from('products').select('*');
    if (error) throw error;
    return data;
  },

  async getProductById(id) {
    if (!supabase) throw new Error('Supabase client not initialized.');
    const { data, error } = await supabase.from('products').select('*').eq('id', id).single();
    if (error) throw error;
    return data;
  },

  async addProduct(product) {
    if (!supabase) throw new Error('Supabase client not initialized.');
    // ID will be generated by Postgres gen_random_uuid()
    const { data, error } = await supabase.from('products').insert([product]).select();
    if (error) throw error;
    return data[0];
  },

  async updateProduct(id, updates) {
    if (!supabase) throw new Error('Supabase client not initialized.');
    // Ensure updated_at is updated
    const { data, error } = await supabase
      .from('products')
      .update({ ...updates, updated_at: new Date().toISOString() })
      .eq('id', id)
      .select();
    if (error) throw error;
    return data[0];
  },

  async deleteProduct(id) {
    if (!supabase) throw new Error('Supabase client not initialized.');
    const { error } = await supabase.from('products').delete().eq('id', id);
    if (error) throw error;
    return true;
  },

  async uploadImage(file) {
    if (!supabase) throw new Error('Supabase client not initialized.');
    
    const fileExt = file.name.split('.').pop();
    const fileName = `${Math.random().toString(36).substring(2, 15)}.${fileExt}`;
    const filePath = `product-images/${fileName}`;
    
    const { error: uploadError } = await supabase.storage
      .from('images')
      .upload(filePath, file);

    if (uploadError) throw uploadError;

    const { data } = supabase.storage
      .from('images')
      .getPublicUrl(filePath);
      
    return data.publicUrl;
  }
};
